---
- name: "Setup Debian"
  hosts: all
  gather_facts: true

  vars_files:
    - vars/main.yml

  handlers:
    - name: "Load handlers"
      ansible.builtin.import_tasks: handlers/main.yml

  pre_tasks:
    - name: "Install required packages for this playbook"
      become: true
      ansible.builtin.apt:
        name:
          - python3-psutil
          - apt-transport-https
        state: present
      tags:
        - always

  tasks:
    - name: "Import tasks"
      ansible.builtin.import_tasks: tasks/main.yml
