- name: "Changing journald configuration"
  become: true
  ansible.builtin.lineinfile:
    path: /etc/systemd/system.conf
    state: present
    regexp: "^#?{{ item | split('=') | first }}"
    line: "{{ item }}"
  loop:
    - DefaultTimeoutStopSec=30s
  notify:
    - reload-systemd

- name: "Add the current user to 'adm' group to read log messages"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: adm
    append: true
    state: present
