- name: "btdu | Get the latest release tag"
  ansible.builtin.uri:
    url: https://github.com/CyberShadow/btdu/releases/latest
    follow_redirects: false
    status_code: 302
  register: r_btdu_latest

- name: "btdu | Download and install"
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/CyberShadow/btdu/releases/download/{{ latest_release_tag }}/btdu-static-x86_64"
    dest: "/usr/local/bin/btdu"
    mode: '0755'
  vars:
    latest_release_tag: "{{ r_btdu_latest.location | split('/') | last }}"
