- name: "CrowTranslate | Install Flatpak"
  become: "{{ flatpak_install_method == 'system' }}"
  community.general.flatpak:
    name: io.crow_translate.CrowTranslate
    remote: flathub
    method: "{{ flatpak_install_method }}"
    state: present
