- name: "JOSM | Install Flatpak"
  become: "{{ flatpak_install_method == 'system' }}"
  community.general.flatpak:
    name: org.openstreetmap.josm
    remote: flathub
    method: "{{ flatpak_install_method }}"
    state: present
