- name: "Obsidian | Install Flatpak"
  become: "{{ flatpak_install_method == 'system' }}"
  community.general.flatpak:
    name: md.obsidian.Obsidian
    remote: flathub
    method: "{{ flatpak_install_method }}"
    state: present
