- name: "QGIS | Install Flatpak"
  become: "{{ flatpak_install_method == 'system' }}"
  community.general.flatpak:
    name: org.qgis.qgis
    remote: flathub
    method: "{{ flatpak_install_method }}"
    state: present
