- name: "Signal | Install Flatpak"
  become: "{{ flatpak_install_method == 'system' }}"
  community.general.flatpak:
    name: org.signal.Signal
    remote: flathub
    method: "{{ flatpak_install_method }}"
    state: present
