- name: "Spotify | Install Flatpak"
  become: "{{ flatpak_install_method == 'system' }}"
  community.general.flatpak:
    name: com.spotify.Client
    remote: flathub
    method: "{{ flatpak_install_method }}"
    state: present
