- name: "Syncthing | Install"
  become: true
  ansible.builtin.apt:
    name: syncthing
    state: present

- name: "Syncthing | Enable service"
  ansible.builtin.systemd:
    name: syncthing.service
    state: started
    enabled: true
    daemon_reload: true
    scope: user
