- name: "Wine | Install Flatpak"
  become: "{{ flatpak_install_method == 'system' }}"
  community.general.flatpak:
    name: org.winehq.Wine
    remote: flathub
    method: "{{ flatpak_install_method }}"
    state: present
