- name: "Wireshark | Install"
  become: true
  ansible.builtin.apt:
    name: wireshark
    state: present

- name: "Add the current user to 'wireshark' group"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: wireshark
    append: true
    state: present
