- name: "ZSH | Install"
  become: true
  ansible.builtin.apt:
    name: zsh
    state: present

- name: "ZSH | Set zsh for the current user"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
    state: present
